name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened


permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
            wip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}